apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - configuration.yaml
  - mysql.yaml
  - applications.yaml
  - cnfc_edge.yaml
  - observability.yaml
patches:
  - target:
      kind: Deployment
      name: inventory-api|orders-api|traffic-generator|lab-worker|lab-control|cnfc-edge-a|cnfc-edge-b
    patch: |-
      - op: add
        path: /spec/strategy
        value: {type: Recreate}
      - op: add
        path: /spec/template/spec/initContainers/0/resources
        value:
          requests: {cpu: 50m, memory: 64Mi}
          limits: {cpu: 500m, memory: 192Mi}
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value: {name: POD_NAMESPACE, valueFrom: {fieldRef: {fieldPath: metadata.namespace}}}
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value: {name: POD_NAME, valueFrom: {fieldRef: {fieldPath: metadata.name}}}
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value: {name: NODE_IP, valueFrom: {fieldRef: {fieldPath: status.hostIP}}}
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value: {name: NODE_EXPORTER_URL, value: 'http://$(NODE_IP):9100/metrics'}
